example.o: example.c
	# gcc example.c -I ../../common/include/ ../../common/lib/librefblas.a ../../common/lib/libcblas.a ../../common/lib/liblapack.a ../../common/lib/liblapacke.a /usr/local/Cellar/gcc/6.2.0/lib/gcc/6/libgfortran.a
		gcc example.c -I ../../common/include/ ../../common/lib/liblapacke.dylib
