# example1.o: example1.c
# 	gcc example1.c ../../common/lib/liblapack.a ../../common/lib/libblas.a ../../common/lib/libgfortran.dylib


FLNAME = example1.

# path to your libraries if you have followed the instructions spsecific for these examples or /usr/local/...
BINDIR = ../../common

NBLAS = true
NGFORTRAN = false
NCBLAS = false
NLAPACK = true
NCLAPACK = false
NLAPACKE = false


include ../../common/Makefile.inc
