sample3.o: sample3.c
	gcc sample3.c -I../../../common/include/ -o sample3.o

#if you have your libblas.a in the common folder
#sample3.o: sample3.c
#	gcc sample3.c -I../../../common/include/ ../../../common/lib/libblas.a ../../../common/lib/libcblas.a -lgfortran -o sample3.o


#sample3.o: sample3.c
#	gcc sample3.c -framework Accelerate -o sample3.o
