time_dgemm.o: time_dgemm.c
	gcc time_dgemm.c -lblas -o time_dgemm.o

#if you have your libblas.a in the common folder
#time_dgemm.o: time_dgemm.c
#	gcc time_dgemm.c ../../../common/lib/libblas.a -o time_dgemm.o
