# testdsyev.o: testdsyev.c
# 	gcc testdsyev.c -llapack


FLNAME = testdsyev.

# path to your libraries if you have followed the instructions spsecific for these examples or /usr/local/...
BINDIR = ../../common

NBLAS = true
NGFORTRAN = false
NCBLAS = false
NLAPACK = true
NCLAPACK = false
NLAPACKE = false


include ../../common/Makefile.inc
