# blas2bC : blas2bC.c
# 	gcc -I../../../common/include/ blas2bC.c ../common/blaio.c  -I../common ../../../common/lib/librefblas.a ../../../common/lib/libcblas.a ../../../common/lib/libgfortran.dylib -o blas2bC.o
