blas2C : blas2C.c
	gcc -I../../../common/include/ blas2C.c ../common/blaio.c  -I../common ../../../common/lib/librefblas.a ../../../common/lib/libcblas.a ../../../common/lib/libgfortran.dylib -o blas2C.o
