blas3C : blas3C.c
	gcc -I../../../common/include/ blas3C.c ../common/blaio.c  -I../common ../../../common/lib/librefblas.a ../../../common/lib/libcblas.a ../../../common/lib/libgfortran.dylib -o blas3C.o
