#example2.o: example2.c
#	gcc example2.c -lblas -o example2.o

#if you have your libblas.a in the common folder
# example2.o: example2.c
# 	gcc example2.c ../../../common/lib/librefblas.a -o example2.o


FLNAME = example2.

# path to your libraries if you have followed the instructions spsecific for these examples or /usr/local/...
BINDIR = ../../../common

NBLAS = true
NGFORTRAN = false
NCBLAS = false
NLAPACK = false
NCLAPACK = false
NLAPACKE = false


include ../../../common/Makefile.inc
