# example1 : example1.c
# 	gcc -I../../../common/include/ example1.c ../../../common/lib/librefblas.a ../../../common/lib/libcblas.a ../../../common/lib/libgfortran.dylib -o example1.o

FLNAME = example1.

# path to your libraries if you have followed the instructions spsecific for these examples or /usr/local/...
BINDIR = ../../../common

NBLAS = true
NGFORTRAN = true
NCBLAS = true
NLAPACK = false
NCLAPACK = false
NLAPACKE = false


include ../../../common/Makefile.inc
